### ISSUE TITLE
use one file for handle telegram and discord

### ISSUE THREAD

**Issue by indmind** [indmind/rin#13]
because we can't use more than one dynos on free Heroku, let's just simplify handle telegram and discord in same file

**Comment by indmind** [comment]
great Idea! I'll be working on this!

**Comment by indmind** [comment]
5stup1d! you forget to add  `STATUS` in procfile 😞

**Comment by indmind** [comment]
https://github.com/indmind/rin/pull/15

**Comment by indmind** [comment]
yeahhhh............................................................. finally!!!!!!! it's working!!!!! 👍  thank you guys for the hard work!! unbelievable!! unbelievable!! let's celebrate this day!!!

**Comment by indmind** [comment]
It's not done yet! we still have some port binding problem, wake up!!!

**Comment by indmind** [comment]
hmm.. let's just create a simple web server to handle this

**Comment by indmind** [comment]
https://github.com/indmind/rin/pull/16 Done!

**Comment by tioirawan** [comment]
that's it guys, I'll close this issue, have a good night :)
