### ISSUE TITLE
New subcommand

### ISSUE THREAD

**Issue by indmind** [indmind/rin#2]
Hey m8, I think we need more sub-command! like posting a code snippet to gist or something

**Comment by indmind** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by indmind** [comment]
good idea, I'll take this!

**Comment by indmind** [comment]
hmm... I think it's too hard, I can't do that, sorry

**Comment by indmate** [comment]
so sad...
